### ISSUE TITLE
Allow mutually exclusive required options

### ISSUE THREAD

**Issue by rguillome** [airlift/airline#79]
As this option in picocli, it would be nice to have a way to provide mutually exclusive options : 

https://picocli.info/#_mutually_exclusive_options

I will make a PR for this one

**Comment by electrum** [comment]
Thanks for your interest in your project. We've actually planned on deprecating this for a while, and have ourselves switched to Picocli. We recommend [Airline 2](https://rvesse.github.io/airline/) or [Picocli](https://picocli.info/) as a replacement.

**Comment by rguillome** [comment]
Ok I didn't see this information before 😞 

[Presto](https://github.com/prestodb/presto) is still using it for its CLI spark launcher. I will recommend them to migrate ! 
Cheers,

**Comment by electrum** [comment]
Presto is a legacy Facebook project. All of the creators (including me) and the community have moved on to [Trino](https://trino.io/). We encourage you to do the same!

**Comment by rohanpednekar** [comment]
Presto is one of the most active, very much community-driven, and fueled by Facebook, Uber, Twitter, and many other active Linux foundation members and a widely used, pure open source community. If I am not wrong [Trino is a Starburst project. ](https://ahana.io/blog/presto-foundation-compared-to-single-vendor-driven-open-source-projects/)

@rguillome, Thanks for bringing [this](https://github.com/prestodb/presto/issues/16236) up. We will take care of your request and you do not have to move to Trino. Stay tuned ✌️

**Comment by rguillome** [comment]
Hi @electrum, it's not the best place to discuss between Presto and Trino but since we run on AWS and I thought Athena and EMR (with presto-on-spark) don't rely on trino but on presto. I would be pleased to have an exchange with you. What would be the best place to do it ?

**Comment by electrum** [comment]
@rguillome please join us on the [Trino Slack](https://trino.io/slack.html). I’m user `david` on there.
